name: Obi
favicon: null
layout_spectrum: 0.19615218392573297
typography_spectrum: 0.7729656263254583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6034896359778941
  lightness: 0.049145961413159966
  saturation: 0.03944932948797941
  rhythmicContrast: 0.18829498393461108
purpose: []
