name: O²
favicon: null
layout_spectrum: 0.19615218392573297
typography_spectrum: 0.7729656263254583
title: Portfolio of Obioma Obiaguzor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131111'
    - '#005883'
    - '#00b7e5'
    - '#8dedf8'
    - '#ffffff'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
